In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
cars1 = pd.read_csv("../data/raw/cars1.csv")

In [3]:
cars2 = pd.read_csv("../data/raw/cars2.csv")

In [4]:
scraped = pd.read_csv("../data/raw/cars_scraped.csv")
scraped.shape

(305, 18)

In [5]:
scraped.head()

,brand,model,variant,year,fuel,transmission,km,body_type,owner,owner_slug,seller_type,locality,price,price_text,search_city,actual_city,listing_url,scraped_at
0,Ford,Ford Ecosport,1.5 TDCi Titanium BSIV,2016,Diesel,Manual,"1,17,300",SUV,1,first-owner,Individual,Pallikaranai,535000,₹5.35 Lakh,chennai,Chennai,https://www.cardekho.com/used-car-details/used...,2026-05-01T15:49:51.147646+00:00
1,MG,MG Astor,Sharp CVT BSVI,2022,Petrol,Automatic,"25,000",SUV,1,first-owner,Dealer,nungambakkam,1365000,₹13.65 Lakh,chennai,Chennai,https://www.cardekho.com/used-car-details/used...,2026-05-01T15:49:51.147670+00:00
2,Volkswagen,Volkswagen Tiguan,2.0 TSI Elegance,2023,Petrol,Automatic,"34,965",SUV,1,first-owner,Dealer,medavakkam,2490000,₹24.90 Lakh,chennai,Chennai,https://www.cardekho.com/used-car-details/used...,2026-05-01T15:49:51.147679+00:00
3,Hyundai,Hyundai i20,1.2 Asta Option,2017,Petrol,Manual,"66,272",Hatchback,1,first-owner,Dealer,Sholinganallur,547000,₹5.47 Lakh,chennai,Chennai,https://www.cardekho.com/buy-used-car-details/...,2026-05-01T15:49:51.147686+00:00
4,Honda,Honda Jazz,1.2 VX i VTEC,2018,Petrol,Manual,"30,000",Hatchback,1,first-owner,Individual,Kotturpuram,570000,₹5.70 Lakh,chennai,Chennai,https://www.cardekho.com/used-car-details/used...,2026-05-01T15:49:51.147693+00:00

In [6]:
scraped.drop(columns=['price_text', 'search_city', 'listing_url', 'scraped_at', 'owner_slug', 'seller_type'], inplace=True)
scraped.head()

,brand,model,variant,year,fuel,transmission,km,body_type,owner,locality,price,actual_city
0,Ford,Ford Ecosport,1.5 TDCi Titanium BSIV,2016,Diesel,Manual,"1,17,300",SUV,1,Pallikaranai,535000,Chennai
1,MG,MG Astor,Sharp CVT BSVI,2022,Petrol,Automatic,"25,000",SUV,1,nungambakkam,1365000,Chennai
2,Volkswagen,Volkswagen Tiguan,2.0 TSI Elegance,2023,Petrol,Automatic,"34,965",SUV,1,medavakkam,2490000,Chennai
3,Hyundai,Hyundai i20,1.2 Asta Option,2017,Petrol,Manual,"66,272",Hatchback,1,Sholinganallur,547000,Chennai
4,Honda,Honda Jazz,1.2 VX i VTEC,2018,Petrol,Manual,"30,000",Hatchback,1,Kotturpuram,570000,Chennai

In [7]:
scraped.shape

(305, 12)

In [8]:
cars1.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Color,Owner,Seller Type,Engine,Max Power,Max Torque,Drivetrain,Length,Width,Height,Seating Capacity,Fuel Tank Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,Grey,First,Corporate,1198 cc,87 bhp @ 6000 rpm,109 Nm @ 4500 rpm,FWD,3990.0,1680.0,1505.0,5.0,35.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,White,Second,Individual,1248 cc,74 bhp @ 4000 rpm,190 Nm @ 2000 rpm,FWD,3995.0,1695.0,1555.0,5.0,42.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,Maroon,First,Individual,1197 cc,79 bhp @ 6000 rpm,112.7619 Nm @ 4000 rpm,FWD,3585.0,1595.0,1550.0,5.0,35.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,Red,First,Individual,1197 cc,82 bhp @ 6000 rpm,113 Nm @ 4200 rpm,FWD,3995.0,1745.0,1510.0,5.0,37.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,Grey,First,Individual,2393 cc,148 bhp @ 3400 rpm,343 Nm @ 1400 rpm,RWD,4735.0,1830.0,1795.0,7.0,55.0

In [9]:
cars1.drop(columns=['Color', 'Max Power', 'Max Torque', 'Drivetrain', 'Length', 'Width', 'Height', 'Fuel Tank Capacity', 'Seller Type'], inplace=True)
cars1.head()

,Make,Model,Price,Year,Kilometer,Fuel Type,Transmission,Location,Owner,Engine,Seating Capacity
0,Honda,Amaze 1.2 VX i-VTEC,505000,2017,87150,Petrol,Manual,Pune,First,1198 cc,5.0
1,Maruti Suzuki,Swift DZire VDI,450000,2014,75000,Diesel,Manual,Ludhiana,Second,1248 cc,5.0
2,Hyundai,i10 Magna 1.2 Kappa2,220000,2011,67000,Petrol,Manual,Lucknow,First,1197 cc,5.0
3,Toyota,Glanza G,799000,2019,37500,Petrol,Manual,Mangalore,First,1197 cc,5.0
4,Toyota,Innova 2.4 VX 7 STR [2016-2020],1950000,2018,69000,Diesel,Manual,Mumbai,First,2393 cc,7.0

In [10]:
cars1.shape

(2059, 11)

In [11]:
cars2.head()

,Unnamed: 0.1,Unnamed: 0,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,0,0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,1,1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,2,2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,3,3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,4,4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74

In [12]:
cars2.drop(columns=['Unnamed: 0.1', 'Unnamed: 0', 'New_Price', 'Power', 'Mileage'], inplace=True)
cars2.head()

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Engine,Seats,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,998 CC,5.0,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,1582 CC,5.0,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,1199 CC,5.0,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,1248 CC,7.0,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,1968 CC,5.0,17.74

In [13]:
cars2.shape

(7253, 10)

In [14]:
cars1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2059 entries, 0 to 2058
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Make              2059 non-null   object
 1   Model             2059 non-null   object
 2   Price             2059 non-null   int64
 3   Year              2059 non-null   int64
 4   Kilometer         2059 non-null   int64
 5   Fuel Type         2059 non-null   object
 6   Transmission      2059 non-null   object
 7   Location          2059 non-null   object
 8   Owner             2059 non-null   object
 9   Engine            1979 non-null   object
 10  Seating Capacity  1995 non-null   float64
dtypes: float64(1), int64(3), object(7)
memory usage: 177.1+ KB

In [15]:
import pandas as pd
import numpy as np

# Align columns
scraped.rename(columns={'actual_city': 'location'}, inplace=True)

# Cars2 price is in Lakhs → convert
cars2['Price'] = cars2['Price'] * 100_000

# Parse brand + model from Cars2 Name column
cars2['brand'] = cars2['Name'].str.split().str[0]
cars2['model'] = cars2['Name'].str.split(n=1).str[1]
cars2.drop(columns=['Name'], inplace=True)

# Normalize column names
cars1.rename(columns={
    'Make': 'brand', 'Model': 'model', 'Price': 'price',
    'Year': 'year', 'Kilometer': 'km', 'Fuel Type': 'fuel',
    'Transmission': 'transmission', 'Location': 'location',
    'Owner': 'owner', 'Seller Type': 'seller_type',
    'Seating Capacity': 'seats'
}, inplace=True)

cars2.rename(columns={
    'Price': 'price', 'Year': 'year', 'Kilometers_Driven': 'km',
    'Fuel_Type': 'fuel', 'Transmission': 'transmission',
    'Location': 'location', 'Owner_Type': 'owner', 'Seats': 'seats'
}, inplace=True)

df_merged = pd.concat([scraped, cars1, cars2], ignore_index=True)

df_merged.head()

,brand,model,variant,year,fuel,transmission,km,body_type,owner,locality,price,location,Engine,seats
0,Ford,Ford Ecosport,1.5 TDCi Titanium BSIV,2016,Diesel,Manual,"1,17,300",SUV,1,Pallikaranai,535000.0,Chennai,NaN,NaN
1,MG,MG Astor,Sharp CVT BSVI,2022,Petrol,Automatic,"25,000",SUV,1,nungambakkam,1365000.0,Chennai,NaN,NaN
2,Volkswagen,Volkswagen Tiguan,2.0 TSI Elegance,2023,Petrol,Automatic,"34,965",SUV,1,medavakkam,2490000.0,Chennai,NaN,NaN
3,Hyundai,Hyundai i20,1.2 Asta Option,2017,Petrol,Manual,"66,272",Hatchback,1,Sholinganallur,547000.0,Chennai,NaN,NaN
4,Honda,Honda Jazz,1.2 VX i VTEC,2018,Petrol,Manual,"30,000",Hatchback,1,Kotturpuram,570000.0,Chennai,NaN,NaN

In [16]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9617 entries, 0 to 9616
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         9617 non-null   object
 1   model         9617 non-null   object
 2   variant       305 non-null    object
 3   year          9617 non-null   int64
 4   fuel          9617 non-null   object
 5   transmission  9617 non-null   object
 6   km            9617 non-null   object
 7   body_type     305 non-null    object
 8   owner         9617 non-null   object
 9   locality      303 non-null    object
 10  price         8383 non-null   float64
 11  location      9617 non-null   object
 12  Engine        9186 non-null   object
 13  seats         9195 non-null   float64
dtypes: float64(2), int64(1), object(11)
memory usage: 1.0+ MB

In [17]:
# Check where price nulls come from
print(df_merged[df_merged['price'].isnull()]['brand'].value_counts().head(10))

brand
Maruti           233
Hyundai          233
Honda            135
Toyota            96
Mercedes-Benz     62
Mahindra          59
Volkswagen        59
Ford              51
Audi              49
BMW               45
Name: count, dtype: int64

In [18]:
df_merged.isnull().sum()

brand              0
model              0
variant         9312
year               0
fuel               0
transmission       0
km                 0
body_type       9312
owner              0
locality        9314
price           1234
location           0
Engine           431
seats            422
dtype: int64

In [19]:
df_merged.drop(columns=['variant', 'body_type', 'locality'], inplace=True)

In [20]:
df_merged.head()

,brand,model,year,fuel,transmission,km,owner,price,location,Engine,seats
0,Ford,Ford Ecosport,2016,Diesel,Manual,"1,17,300",1,535000.0,Chennai,NaN,NaN
1,MG,MG Astor,2022,Petrol,Automatic,"25,000",1,1365000.0,Chennai,NaN,NaN
2,Volkswagen,Volkswagen Tiguan,2023,Petrol,Automatic,"34,965",1,2490000.0,Chennai,NaN,NaN
3,Hyundai,Hyundai i20,2017,Petrol,Manual,"66,272",1,547000.0,Chennai,NaN,NaN
4,Honda,Honda Jazz,2018,Petrol,Manual,"30,000",1,570000.0,Chennai,NaN,NaN

In [21]:
df_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9617 entries, 0 to 9616
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   brand         9617 non-null   object
 1   model         9617 non-null   object
 2   year          9617 non-null   int64
 3   fuel          9617 non-null   object
 4   transmission  9617 non-null   object
 5   km            9617 non-null   object
 6   owner         9617 non-null   object
 7   price         8383 non-null   float64
 8   location      9617 non-null   object
 9   Engine        9186 non-null   object
 10  seats         9195 non-null   float64
dtypes: float64(2), int64(1), object(8)
memory usage: 826.6+ KB

In [22]:
df_merged.dropna(inplace=True)

In [23]:
df_merged.shape

(7956, 11)

In [24]:
df_merged.rename(columns={
    'brand': 'Brand', 'model': 'Model', 'price': 'Price',
    'year': 'Year', 'km': 'Km', 'fuel': 'Fuel',
    'transmission': 'Transmission', 'location': 'Location',
    'owner': 'Owner','seats': 'Seats',
}, inplace=True)

In [26]:
df_merged['Engine'] = df_merged['Engine'].str.extract('(\d+)').astype(int)

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\HP\AppData\Local\Temp\ipykernel_9260\1485442504.py:1: SyntaxWarning: invalid escape sequence '\d'
  df_merged['Engine'] = df_merged['Engine'].str.extract('(\d+)').astype(int)

In [27]:
df_merged.to_csv("../data/processed/cars_processed.csv", index=False)